"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOCKID = exports.LOCK_CLIENTID = exports.LOCKAPI = exports.R = exports.COM_DIST = exports.COM_LNG = exports.COM_LAT = exports.SECRET_KEY = exports.DB_USERNAME = exports.DB_PASSWORD = exports.DB_NAME = exports.DB_HOST = exports.DB_PORT = exports.DB_URI = exports.PORT = void 0;
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const DB_URI = process.env.DB_URI;
exports.DB_URI = DB_URI;
const DB_HOST = process.env.DB_HOST;
exports.DB_HOST = DB_HOST;
const DB_NAME = process.env.DB_NAME;
exports.DB_NAME = DB_NAME;
const DB_PORT = process.env.DB_PORT;
exports.DB_PORT = DB_PORT;
const DB_PASSWORD = process.env.DB_PASSWORD;
exports.DB_PASSWORD = DB_PASSWORD;
const DB_USERNAME = process.env.DB_USERNAME;
exports.DB_USERNAME = DB_USERNAME;
const SECRET_KEY = process.env.SECRET_KEY;
exports.SECRET_KEY = SECRET_KEY;
const PORT = process.env.PORT;
exports.PORT = PORT;
const COM_LAT = process.env.COM_LAT;
exports.COM_LAT = COM_LAT;
const COM_LNG = process.env.COM_LNG;
exports.COM_LNG = COM_LNG;
const COM_DIST = process.env.COM_DIST;
exports.COM_DIST = COM_DIST;
const R = process.env.R;
exports.R = R;
const LOCKAPI = process.env.LOCKAPI;
exports.LOCKAPI = LOCKAPI;
const LOCK_CLIENTID = process.env.CLIENTID;
exports.LOCK_CLIENTID = LOCK_CLIENTID;
const LOCKID = process.env.LOCKID;
exports.LOCKID = LOCKID;
